import { useState } from 'react'
import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import {
    AiFillTwitterCircle,
    AiFillLinkedin,
    AiFillGithub,
} from 'react-icons/ai'
import Image from 'next/image'
import avatar from './../public/dev-ed-wave.png'
import design from './../public/design.png'
import code from './../public/code.png'
import consulting from './../public/consulting.png'
import web1 from './../public/web1.jpg'
import web2 from './../public/web2.jpg'
import web3 from './../public/web3.jpg'
import web4 from './../public/web4.jpg'
import web5 from './../public/web5.png'
import web6 from './../public/web6.png'

export default function Home() {
    const [darkMode, setDarkMode] = useState(false)
    return (
        <div className={darkMode ? 'dark' : ''}>
            <Head>
                <title> Ahmed Raed 101 portfolio</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 '>
                <section className='min-h-screen'>
                    <nav className='py-10 mb-12 flex justify-between'>
                        <h1 className='text-xl font-burtons dark:text-blue-50'>
                            @ahmedraed101
                        </h1>
                        <ul className='flex items-center'>
                            <li>
                                <BsFillMoonStarsFill
                                    className='cursor-pointer text-2xl dark:text-blue-50'
                                    onClick={() => {
                                        setDarkMode(!darkMode)
                                    }}
                                />
                            </li>
                            <li>
                                <a
                                    href='#'
                                    className='bg-gradient-to-r from-cyan-500  to-teal-500 select-none text-white px-4 py-2 rounded-md ml-8'
                                >
                                    Resume
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <div className='text-center p-10'>
                        <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl '>
                            Ahmed Raed
                        </h2>
                        <h3 className='text-2xl py-2 md:text-3xl dark:text-blue-50'>
                            Web Developer
                        </h3>
                        <p className='text-md py-5 leading-8 text-gray-800  max-w-lg mx-auto md:text-xl dark:text-blue-50'>
                            Student who is willing to learn and grow, love web
                            development, and seeking junior software developer
                            role.
                        </p>
                    </div>
                    <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
                        <a
                            href='https://twitter.com/ahmedraed101'
                            rel='noreferrer'
                            target='_blank'
                        >
                            <AiFillTwitterCircle className='duration-100 hover:text-teal-500' />
                        </a>
                        <a
                            href='https://www.linkedin.com/in/ahmedraed101/'
                            rel='noreferrer'
                            target='_blank'
                        >
                            <AiFillLinkedin className='duration-100 hover:text-teal-500' />
                        </a>
                        <a
                            href='https://github.com/ahmedraed101'
                            rel='noreferrer'
                            target='_blank'
                        >
                            <AiFillGithub className='duration-100 hover:text-teal-500' />
                        </a>
                    </div>
                    <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
                        <Image
                            src={avatar}
                            alt="ahmed's raed image"
                            layout='fill'
                            objectFit='cover'
                        />
                    </div>
                </section>
                <section>
                    <div>
                        <h3 className='text-3xl py-1 dark:text-blue-50 mt-20'>
                            About Me
                        </h3>
                        <p className='text-md py-2 leading-8 text-gray-800 dark:text-blue-50'>
                            Passionate junior full-stack developer with a focus
                            on backend development. Enthusiastic about starting
                            a web development career. Solid foundation in
                            front-end and back-end technologies. Committed to
                            continuous learning and making a positive impact.
                            Excited to contribute, grow professionally, and make
                            a difference in web development.
                        </p>
                        <p className='text-md py-2 leading-8 text-gray-80 dark:text-blue-50'>
                            I am enthusiastic about exploring new technologies,
                            and the following are the ones I have utilized in my
                            projects thus far.{' '}
                        </p>
                    </div>
                    <div className='lg:flex gap-10'>
                        <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
                            <Image
                                src={code}
                                alt='design'
                                width={100}
                                height={100}
                                className='mx-auto'
                            />
                            <h3 className='text-lg font-meduim pt-8 pb-2'>
                                Languages
                            </h3>
                            <p className='py-2'>
                                programming languages used in projects
                            </p>
                            <h4 className='py-4 text-teal-600'>JavaScript</h4>
                            <p className='text-gray-800 py-1'>C</p>
                            <p className='text-gray-800 py-1'>Python</p>
                            <p className='text-gray-800 py-1'>HTML5 & CSS3</p>
                        </div>
                        <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
                            <Image
                                src={design}
                                alt='code'
                                width={100}
                                height={100}
                                className='mx-auto'
                            />
                            <h3 className='text-lg font-meduim pt-8 pb-2'>
                                Front-End
                            </h3>
                            <p className='py-2'>
                                Front-End Frameworks & css libraries used in my
                                projects
                            </p>
                            <h4 className='py-4 text-teal-600'>ReactJS</h4>
                            <p className='text-gray-800 py-1'>Redux</p>
                            <p className='text-gray-800 py-1'>Tailwind</p>
                            <p className='text-gray-800 py-1'>Sass</p>
                        </div>
                        <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
                            <Image
                                src={code}
                                alt='consulting'
                                width={100}
                                height={100}
                                className='mx-auto'
                            />
                            <h3 className='text-lg font-meduim pt-8 pb-2'>
                                BackEnd
                            </h3>
                            <p className='py-2'>
                                Backend frameworks & libraries used in my
                                projects
                            </p>
                            <h4 className='py-4 text-teal-600'>Express</h4>
                            <p className='text-gray-800 py-1'>PostgreSQL</p>
                            <p className='text-gray-800 py-1'>MongoDB</p>
                            <p className='text-gray-800 py-1'>JWT</p>
                        </div>
                    </div>
                </section>
                <section>
                    <div>
                        <h3 className='text-3xl dark:text-blue-50 py-1'>
                            Portfolio
                        </h3>
                        <p className='text-md py-2 leading-8 text-gray-800 dark:text-blue-50'>
                            Some of my hosted projects and ones from github
                        </p>
                    </div>
                    <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
                        <div className='basis-1/3 flex-1'>
                            <a
                                href='https://node-weather-map.netlify.app/'
                                rel='noreferrer'
                                target='_blank'
                            >
                                <Image
                                    alt='portfolio'
                                    src={web1}
                                    className='roundex-lg object-cover'
                                    width={'100%'}
                                    height={'100%'}
                                    layout={'responsive'}
                                />
                            </a>
                        </div>
                        <div className='basis-1/3 flex-1'>
                            <a
                                href='https://ahmedraed101.github.io/photo_edit_web/'
                                rel='noreferrer'
                                target='_blank'
                            >
                                <Image
                                    alt='portfolio'
                                    src={web2}
                                    className='roundex-lg object-cover'
                                    width={'100%'}
                                    height={'100%'}
                                    layout={'responsive'}
                                />
                            </a>
                        </div>
                        <div className='basis-1/3 flex-1'>
                            <a
                                href='https://ahmedraed-movieland.netlify.app/'
                                rel='noreferrer'
                                target='_blank'
                            >
                                <Image
                                    alt='portfolio'
                                    src={web3}
                                    className='roundex-lg object-cover'
                                    width={'100%'}
                                    height={'100%'}
                                    layout={'responsive'}
                                />
                            </a>
                        </div>
                        <div className='basis-1/3 flex-1'>
                            <a
                                href='https://ramadan-jana.netlify.app/'
                                rel='noreferrer'
                                target='_blank'
                            >
                                <Image
                                    alt='portfolio'
                                    src={web4}
                                    className='roundex-lg object-cover'
                                    width={'100%'}
                                    height={'100%'}
                                    layout={'responsive'}
                                />
                            </a>
                        </div>
                        {/* <div className='basis-1/3 flex-1'>
                            <Image
                                alt='portfolio'
                                src={web5}
                                className='roundex-lg object-cover'
                                width={'100%'}
                                height={'100%'}
                                layout={'responsive'}
                            />
                        </div>
                        <div className='basis-1/3 flex-1'>
                            <Image
                                alt='portfolio'
                                src={web6}
                                className='roundex-lg object-cover'
                                width={'100%'}
                                height={'100%'}
                                layout={'responsive'}
                            />
                        </div> */}
                    </div>
                </section>
            </main>
        </div>
    )
}
